### ISSUE TITLE
Replacing existing splitter crashes the game

### ISSUE THREAD

**Issue by Tauschung** [smuething/SatisfactoryAutoSplitters#1]
The hologram snaps properly to existing splitters to upgrade them, but attempting to upgrade to an auto splitter immediately crashes the game.

**Comment by smuething** [comment]
Yes, that's bugging me as well. The mod contains no code at all to make upgrades work, the hologram shows up because the building reuses the standard splitter hologram. I'll have to get some help in the Discord to fix that...

**Comment by smuething** [comment]
Fixed in 0.3.0.
