### ISSUE TITLE
Auto splitters not lining up with vanilla splitters on foundation grids

### ISSUE THREAD

**Issue by Tauschung** [smuething/SatisfactoryAutoSplitters#2]
Note the bounding boxes not lining up. You can't attach conveyors between an auto splitter and a vanilla splitter directly adjacent to each other like this.
![20210524222822_1](https://user-images.githubusercontent.com/60052170/119430878-88930f00-bcdf-11eb-8b64-9a1e21a5ef8b.jpg)

**Comment by smuething** [comment]
Thanks for the report! That will probably just require some tweaking of the model bounding box (I hope).

**Comment by smuething** [comment]
Should be fixed in 0.2.0, uploading to ficsit.app right now :)
