### ISSUE TITLE
Recurrent crashes

### ISSUE THREAD

**Issue by gm-crake** [smuething/SatisfactoryAutoSplitters#3]
Hi, this mod crashes every time I try to connect one splitter to another and then to a smelter. Not sure what's going on. I've attached my debug info:    
[SMMDebug_2021-6-3_18-31-42.zip](https://github.com/smuething/SatisfactoryAutoSplitters/files/6593641/SMMDebug_2021-6-3_18-31-42.zip)

**Comment by neekz0r** [comment]
Not the developer, but for what it's worth that behavior works fine for me. ![Here is a screenshot as proof.](https://user-images.githubusercontent.com/7443593/120938497-cfadd680-c6c7-11eb-9135-4a8cdae36057.jpg) (And also I have another smelter setup doing the same thing.

Perhaps try disabling some other mods, if any?

**Comment by smuething** [comment]
Does this still happen? 0.3.9 should have taken care of nonsense like that...

**Comment by gm-crake** [comment]
sorry for keeping this open - you're right @smuething , it was fixed as soon as I updated to 0.3.9. Thanks!
